# Generated by Django 6.0.1 on 2026-02-01 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อห้องเรียน')),
                ('year_level', models.IntegerField(verbose_name='ชั้นปี')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='รหัสวิชา')),
                ('name_th', models.CharField(max_length=200, verbose_name='ชื่อวิชา (ไทย)')),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อวิชา (อาหรับ)')),
                ('category', models.CharField(choices=[('ACADEMIC', 'วิชาสามัญ'), ('RELIGIOUS', 'วิชาศาสนา')], max_length=15)),
                ('credit', models.FloatField(default=1.0, verbose_name='หน่วยกิต')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True, verbose_name='เลขประจำตัวนักเรียน')),
                ('gpax', models.FloatField(default=0.0, verbose_name='เกรดเฉลี่ยสะสม')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sms.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2567)),
                ('grade', models.FloatField(blank=True, null=True, verbose_name='เกรดที่ได้')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sms.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term', 'year')},
            },
        ),
    ]
