# Generated by Django 6.0.1 on 2026-02-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('executive', 'Executive'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='STUDENT', max_length=10),
        ),
    ]
