# Generated by Django 6.0.1 on 2026-02-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRESENT', 'มาเรียน'), ('LATE', 'สาย'), ('ABSENT', 'ขาด')], default='PRESENT', max_length=10)),
                ('method', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='sms.student')),
            ],
        ),
    ]
