# Generated by Django 6.0.1 on 2026-02-04 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='sms.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อบทเรียน')),
                ('content', models.TextField(help_text='เนื้อหาบทเรียน (รองรับ Markdown หรือ HTML)', verbose_name='เนื้อหา')),
                ('video_url', models.URLField(blank=True, help_text='ลิงก์วิดีโอจาก YouTube/Vimeo', verbose_name='ลิงก์วิดีโอ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับบทเรียน')),
                ('enable_ai_chat', models.BooleanField(default=True, verbose_name='เปิดใช้งาน AI Tutor')),
                ('enable_quiz', models.BooleanField(default=True, verbose_name='เปิดใช้งานระบบ Quiz')),
                ('enable_video', models.BooleanField(default=True, verbose_name='แสดงวิดีโอประกอบ')),
                ('ai_complexity', models.CharField(choices=[('easy', 'พื้นฐาน'), ('medium', 'ปานกลาง'), ('hard', 'ขั้นสูง')], default='medium', max_length=20, verbose_name='ระดับความยากของ AI')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course')),
            ],
            options={
                'verbose_name': 'บทเรียน',
                'verbose_name_plural': 'บทเรียน',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_students', models.ManyToManyField(related_name='parents', to='sms.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('correct_answer', models.IntegerField(help_text='ใส่เลข 0-3 (0=ข้อแรก, 1=ข้อสอง...)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.CharField(default='6/1', max_length=10, verbose_name='ห้องเรียน')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='เลขประจำตัวนักเรียน')),
                ('classroom', models.CharField(max_length=10, verbose_name='ห้องเรียน (เช่น 6/1)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
