# Generated by Django 6.0.1 on 2026-02-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_leaverequest_schedule_attendance_termgrade'),
        ('sms', '0002_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'การเข้าเรียน', 'verbose_name_plural': 'การเข้าเรียน'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.classroom', verbose_name='ห้องเรียน'),
        ),
    ]
